# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/satellite_page.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SatPage(object):
    def setupUi(self, SatPage):
        SatPage.setObjectName("SatPage")
        SatPage.resize(550, 553)
        SatPage.setMinimumSize(QtCore.QSize(550, 553))
        SatPage.setMaximumSize(QtCore.QSize(550, 553))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("FP_Satellite_icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SatPage.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(SatPage)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SatPage)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(SatPage)
        self.line.setGeometry(QtCore.QRect(-10, 150, 591, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lvPasses = QtWidgets.QListWidget(SatPage)
        self.lvPasses.setGeometry(QtCore.QRect(10, 170, 371, 381))
        self.lvPasses.setObjectName("lvPasses")
        self.btnPlot = QtWidgets.QPushButton(SatPage)
        self.btnPlot.setGeometry(QtCore.QRect(390, 170, 151, 41))
        self.btnPlot.setObjectName("btnPlot")
        self.nameLabel = QtWidgets.QLabel(SatPage)
        self.nameLabel.setGeometry(QtCore.QRect(140, 30, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.label_3 = QtWidgets.QLabel(SatPage)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 54, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.numberLabel = QtWidgets.QLabel(SatPage)
        self.numberLabel.setGeometry(QtCore.QRect(140, 50, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numberLabel.setFont(font)
        self.numberLabel.setObjectName("numberLabel")
        self.label_5 = QtWidgets.QLabel(SatPage)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inclinationLabel = QtWidgets.QLabel(SatPage)
        self.inclinationLabel.setGeometry(QtCore.QRect(140, 70, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inclinationLabel.setFont(font)
        self.inclinationLabel.setObjectName("inclinationLabel")
        self.label_4 = QtWidgets.QLabel(SatPage)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ascensionLabel = QtWidgets.QLabel(SatPage)
        self.ascensionLabel.setGeometry(QtCore.QRect(140, 90, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ascensionLabel.setFont(font)
        self.ascensionLabel.setObjectName("ascensionLabel")
        self.label_6 = QtWidgets.QLabel(SatPage)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.eccentricityLabel = QtWidgets.QLabel(SatPage)
        self.eccentricityLabel.setGeometry(QtCore.QRect(140, 110, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eccentricityLabel.setFont(font)
        self.eccentricityLabel.setObjectName("eccentricityLabel")
        self.label_7 = QtWidgets.QLabel(SatPage)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.argumentLabel = QtWidgets.QLabel(SatPage)
        self.argumentLabel.setGeometry(QtCore.QRect(140, 130, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.argumentLabel.setFont(font)
        self.argumentLabel.setObjectName("argumentLabel")
        self.label_8 = QtWidgets.QLabel(SatPage)
        self.label_8.setGeometry(QtCore.QRect(310, 30, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.anomalyLabel = QtWidgets.QLabel(SatPage)
        self.anomalyLabel.setGeometry(QtCore.QRect(410, 30, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.anomalyLabel.setFont(font)
        self.anomalyLabel.setObjectName("anomalyLabel")
        self.label_9 = QtWidgets.QLabel(SatPage)
        self.label_9.setGeometry(QtCore.QRect(310, 50, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.motionLabel = QtWidgets.QLabel(SatPage)
        self.motionLabel.setGeometry(QtCore.QRect(410, 50, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.motionLabel.setFont(font)
        self.motionLabel.setObjectName("motionLabel")
        self.line_2 = QtWidgets.QFrame(SatPage)
        self.line_2.setGeometry(QtCore.QRect(290, 30, 16, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(SatPage)
        QtCore.QMetaObject.connectSlotsByName(SatPage)

    def retranslateUi(self, SatPage):
        _translate = QtCore.QCoreApplication.translate
        SatPage.setWindowTitle(_translate("SatPage", "Satellite information"))
        self.label.setText(_translate("SatPage", "Satellite information:"))
        self.label_2.setText(_translate("SatPage", "Name:"))
        self.btnPlot.setText(_translate("SatPage", "Plot pass"))
        self.nameLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_3.setText(_translate("SatPage", "Number:"))
        self.numberLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_5.setText(_translate("SatPage", "Inclination:"))
        self.inclinationLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_4.setText(_translate("SatPage", "Right ascension:"))
        self.ascensionLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_6.setText(_translate("SatPage", "Eccentricity:"))
        self.eccentricityLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_7.setText(_translate("SatPage", "Argument of perigee:"))
        self.argumentLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_8.setText(_translate("SatPage", "Mean anomaly:"))
        self.anomalyLabel.setText(_translate("SatPage", "TextLabel"))
        self.label_9.setText(_translate("SatPage", "Mean motion:"))
        self.motionLabel.setText(_translate("SatPage", "TextLabel"))

